import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/app/theme/colors";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joseph Project App",
  description: "Generated by Dev. Luis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
    </ThemeProvider>
  );
}
